### ISSUE TITLE
Zig header file format

### ISSUE THREAD

**Issue by justinbalexander** [vegecode/svd2zig#3]
The current way to write or read from a register is using the generated PERIPHERAL_REGISTER_Write and PERIPHERAL_REGISTER_Read functions. I did it that way initially as some registers are read or write only and thus only the correct functions would be generated. It also has the benefit of automatically applying any necessary mask such that DNU or Reserved bits are not modified. 

I am finding that using the supplied definitions results in hideous and verbose code. Register modification already looks bad in C, but it's seriously ugly with this method.

Consider:

```zig
const reg = @import("STM32F7x7.zig");

fn enableFPU() void {
    // Set CP10 and CP11 Full Access
    var cpacr = reg.FPU_CPACR_CPACR_Read();
    cpacr |= reg.FPU_CPACR_CPACR_CP_Mask;
    reg.FPU_CPACR_CPACR_Write(cpacr);
}

```

That is the nicest looking code I could write using the _Read and _Write functionality.

This proposal is to drop the read and write functions in favor of having instead a single PERIPHERAL_REGISTER_Ptr field that is just a hard coded volatile pointer to the memory location.

The code will become a lot more "C" like and the example above becomes:

```zig
const reg = @import("STM32F7x7.zig");

fn enableFPU() void {
    // Set CP10 and CP11 Full Access
    reg.FPU_CPACR_CPACR_Ptr.* |= reg.FPU_CPACR_CPACR_CP_Mask;
}
```

This style of code will be familiar to any embedded programmer. Also, there is no excuse to not read the datasheet! You will have to read it and understand it thoroughly to use the registers regardless.

Questions to consider:

Will this affect the generation of code for registers that exist as a series? For example, PIO1, PIO2, etc. are often shown in datasheets as being an array of indexable structs PIO[n]. I'm not sure but I think this style will be unattainable in current Zig syntax as variables are not allowed to volatile so we couldn't have an array of volatile structs.

**Comment by justinbalexander** [comment]
I'm in favor of the change so I will push the modifications in a few days if no further feedback is given.

**Comment by markfirmware** [comment]
I'm using a comptime function to map extern struct, arrays, or scalars:

    pub fn mmio(address: u32, comptime mmio_type: type) *volatile mmio_type {
        return @intToPtr(*volatile mmio_type, address);
    }

As in:

    pub const Wdt = struct {
        pub const reload_request_registers = mmio(0x40010600, extern struct {
            reload_request: [8]u32,
        });

        pub const registers = mmio(0x40010504, extern struct {
            counter_reset_value: u32,
            reload_request_enable: u32,
        });

        pub const tasks = mmio(0x40010000, extern struct {
            start: u32,
        });
    };

It doesn't need .* at all since even for a scalar I put it inside an extern struct. This is probably a lot like what you had before you flattened things.

One thing though is that the volatile keyword is slated for removal and I haven't yet spent any time considering that.

**Comment by justinbalexander** [comment]
I don't think the proposal to remove volatile has been accepted yet. Maybe you should comment on that issue. What I hoped to communicate with my post on that issue is that the volatile keyword is unfairly maligned and in fact I think we should keep C semantics. My intuition is that the vast majority of embedded C programmers will agree. I find the hatred of the anti-volatile movement to be baffling, personally. I couldn't care less what Rust does, FWIW. Zig is the future I think.

I really like that method of using an extern struct. Very sneaky. It would be more difficult to code the translator though. What about fields? How are you handling namespacing?

That is an extra '.' operator though. What do you think of this counter proposal?

```zig
pub const Wdt = mmio(0x40010500, extern struct {
  start: u32,
  padding0: [(0x40010504 - 0x40010004) / 4]u32,
  counter_reset_value: u32,
  reload_request_enable: u32,
  padding1: [(0x40010600 - 0x400105C0) / 4]u32,
  reload_request: [8]u32,
});
```

It eliminates a dot at least.

I probably won't put in the time to do this change until I get further along in my burnedhead project. This sounds like good blog material to promote Zig.

I will put in the minimal time to do the pointer change in the near future though.

**Comment by markfirmware** [comment]
That does seem reasonable given that the padding sizes are generated automatically from the .svd.

**Comment by justinbalexander** [comment]
Done in 67bf414
